services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /home/hoosh/.cache/huggingface:/hf_ro:ro
      - ./data:/app
    environment:
      - HF_DATASETS_OFFLINE=1
      - HF_HUB_OFFLINE=1
      - HF_HOME=/hf_ro
