services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /home/hoosh/.cache/huggingface:/hf_ro
      - ./data:/app
    environment:
      - HF_HOME=/hf_ro
      - DS_NAME=Raziullah/librispeech_small_asr_fine-tune
      - DS_SPLIT=test[:1%]
